services:
  redis:
    image: redis
    container_name: "redis-grimoire"
    ports:
      - 6370:6379

  postgres:
    image: postgres
    container_name: "postgres-grimoire"
    environment:
      - POSTGRES_USER=grimoire
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=grimoire
    ports:
      - 5430:5432
    volumes:
      - ./db_data/data:/var/lib/postgresql/data

volumes:
  db:
    driver: local
