services:
  grimoire:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    container_name: grimoire
    env_file: .env_template
    ports:
      - 5005:5005

  redis:
    image: redis
    container_name: "redis-grimoire"
    ports:
      - 6370:6379

  postgres:
    image: pgvector/pgvector:pg16
    container_name: "postgres-grimoire"
    environment:
      - POSTGRES_USER=grimoire
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=grimoire
    ports:
      - 5430:5432
    volumes:
      - db:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    command: [ "python", "-m", "unittest", "discover" ]

  lint:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    command: [ "ruff", "check", "." ]

volumes:
  db:
    driver: local
