defaults = {
    "CELERY_BROKER_URL": "redis://127.0.0.1:6379/0",
    "REDIS_HOST": "localhost",
    "REDIS_PORT": 6379,
    "CACHE_EXPIRE_TIME": 86400,
    "DB_ENGINE": "postgresql+psycopg2://grimoire:secretpassword@127.0.0.1:5432/grimoire",
    "DEBUG": False,
    "LOG_PROMPTS": False,
    "LOG_FILES": False,
    "AUTH_KEY": "",
    "ENCRYPTION_KEY": "",
    "prefer_gpu": False,
    "match_distance": 80,
    "summarization_api": {
        "backend": "GenericOAI",
        "url": "",
        "auth_key": "",
        "context_length": 4096,
        "system_sequence": "",
        "system_suffix": "",
        "input_sequence": "### Instruction:\n",
        "input_suffix": "",
        "output_sequence": "\n### Response:\n",
        "output_suffix": "",
        "first_output_sequence": "",
        "last_output_sequence": "",
    },
    "summarization": {
        "prompt": "{previous_summary}\n{messages}\n{input_sequence}Describe {term}.{input_suffix}{output_sequence}",
        "limit_rate": 1,
        "bos_token": "<s>",
        "max_tokens": 300,
        "params": {"min_p": 0.1, "rep_pen": 1.0, "temperature": 0.6, "stop": ["</s>"], "stop_sequence": ["</s>"]},
    },
    "tokenization": {"prefer_local_tokenizer": True, "local_tokenizer": "oobabooga/llama-tokenizer"},
    "secondary_database": {"enabled": False, "db_engine": "", "message_encryption": "aesgcm", "encryption_key": ""},
}
