REDIS_HOST: !env REDIS_HOST
REDIS_PORT: !env REDIS_PORT
CACHE_EXPIRE_TIME: !env CACHE_EXPIRE_TIME
DB_ENGINE: !env DB_ENGINE
DEBUG: !env DEBUG
LOG_PROMPTS: !env LOG_PROMPTS
LOG_FILES: !env LOG_FILES
AUTH_KEY: !env AUTH_KEY
ENCRYPTION_KEY: !env ENCRYPTION_KEY
prefer_gpu: !env PREFER_GPU
match_distance: !env MATCH_DISTANCE

summarization_api:
  backend: !env SUMMARIZATION_BACKEND
  url: !env SUMMARIZATION_API_URL
  auth_key: !env SUMMARIZATION_API_AUTH
  context_length: !env SUMMARIZATION_CONTEXT
  system_sequence: !env SYSTEM_SEQUENCE
  system_suffix: !env SYSTEM_SUFFIX
  input_sequence: !env INPUT_SEQUENCE
  input_suffix: !env INPUT_SUFFIX
  output_sequence: !env OUTPUT_SEQUENCE
  output_suffix: !env OUTPUT_SUFFIX
  first_output_sequence: !env FIRST_OUTPUT_SEQUENCE
  last_output_sequence: !env LAST_OUTPUT_SEQUENCE

summarization:
  prompt: !env SUMMARIZATION_PROMPT
  limit_rate: !env LIMIT_RATE
  bos_token: !env BOS_TOKEN
  max_tokens: !env MAX_TOKENS
  params': {'min_p': 0.1, 'rep_pen': 1.0, 'temperature': 0.6, 'stop': ["</s>"], 'stop_sequence': ["</s>"]}

tokenization:
  prefer_local_tokenizer: !env PREFER_LOCAL_TOKENIZER
  local_tokenizer: !env LOCAL_TOKENIZER

secondary_database:
  enabled: !env SECONDARY_DATABASE
  db_engine: !env SECONDARY_DB_ENGINE
  message_encryption: !env SECONDARY_ENCRYPTION
  encryption_key: !env SECONDARY_ENCRYPTION_KEY