DB_ENGINE: !env DB_ENGINE
DEBUG: !env DEBUG
LOG_PROMPTS: !env LOG_PROMPTS
LOG_FILES: !env LOG_FILES
AUTH_KEY: !env AUTH_KEY
ENCRYPTION_KEY: !env ENCRYPTION_KEY
prefer_gpu: !env PREFER_GPU
match_distance: !env MATCH_DISTANCE

redis:
  REDIS_HOST: !env REDIS_HOST
  REDIS_SENTINEL: !env REDIS_SENTINEL
  SENTINEL_MASTER_NAME: !env SENTINEL_MASTER_NAME
  REDIS_TLS: !env REDIS_TLS
  CACHE_EXPIRE_TIME: !env CACHE_EXPIRE_TIME

summarization_api:
  backend: !env SUMMARIZATION_BACKEND
  url: !env SUMMARIZATION_API_URL
  auth_key: !env SUMMARIZATION_API_AUTH
  context_length: !env SUMMARIZATION_CONTEXT
  system_sequence: !env SYSTEM_SEQUENCE
  system_suffix: !env SYSTEM_SUFFIX
  input_sequence: !env INPUT_SEQUENCE
  input_suffix: !env INPUT_SUFFIX
  output_sequence: !env OUTPUT_SEQUENCE
  output_suffix: !env OUTPUT_SUFFIX
  first_output_sequence: !env FIRST_OUTPUT_SEQUENCE
  last_output_sequence: !env LAST_OUTPUT_SEQUENCE
  bos_token: !env BOS_TOKEN

summarization:
  prompt: !env SUMMARIZATION_PROMPT
  limit_rate: !env LIMIT_RATE
  max_tokens: !env MAX_TOKENS
  params: !env SUMMARIZATION_PARAMS

tokenization:
  prefer_local_tokenizer: !env PREFER_LOCAL_TOKENIZER
  local_tokenizer: !env LOCAL_TOKENIZER

secondary_database:
  enabled: !env SECONDARY_DATABASE
  db_engine: !env SECONDARY_DB_ENGINE
  message_encryption: !env SECONDARY_ENCRYPTION
  encryption_key: !env SECONDARY_ENCRYPTION_KEY