"""changes to message table

Revision ID: 1ab1bd4ac856
Revises: 0d440b092601
Create Date: 2024-08-06 16:28:36.067545

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ab1bd4ac856"
down_revision: str | None = "0d440b092601"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("external_id", sa.String(), nullable=True))
    op.drop_column("message", "summary")
    op.drop_column("message", "summary_tokens")
    op.drop_column("message", "message_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("message_tokens", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("message", sa.Column("summary_tokens", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("message", sa.Column("summary", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("message", "external_id")
    # ### end Alembic commands ###
