"""add tables for multiuser

Revision ID: 7fc7a59c8cf5
Revises: 4b9a98eb28b8
Create Date: 2024-04-04 13:26:25.799490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc7a59c8cf5'
down_revision: Union[str, None] = '4b9a98eb28b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_column('knowledge', 'chat_id')
    op.add_column('knowledge', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'knowledge', 'chat', ['chat_id'], ['id'])

    op.drop_column('message', 'chat_id')
    op.add_column('message', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'chat_id')
    op.add_column('message', sa.Column('chat_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint('knowledge_chat_id_fkey', 'knowledge', type_='foreignkey')
    op.drop_column('knowledge', 'chat_id')
    op.add_column('knowledge', sa.Column('chat_id', sa.VARCHAR(), nullable=False))
    op.drop_table('chat')
    op.drop_table('user')
    # ### end Alembic commands ###
