"""add vector fields

Revision ID: 4a9f2c2e6c50
Revises: 07e47a0ce65d
Create Date: 2024-09-11 19:16:57.155693

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a9f2c2e6c50"
down_revision: str | None = "07e47a0ce65d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column("knowledge", sa.Column("vector_embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    op.add_column("message", sa.Column("vector_embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "vector_embedding")
    op.drop_column("knowledge", "vector_embedding")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
