"""remove_spacy_doc

Revision ID: 0d440b092601
Revises: 5b0a30e8bcee
Create Date: 2024-07-16 13:46:50.375933

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d440b092601"
down_revision: str | None = "5b0a30e8bcee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "spacy_doc")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("spacy_doc", postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
