"""add summary entry field

Revision ID: 07e47a0ce65d
Revises: 603509951db4
Create Date: 2024-08-16 21:28:32.333898

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07e47a0ce65d"
down_revision: str | None = "603509951db4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge",
        sa.Column(
            "summary_entry", sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True
        ),
    )
    op.alter_column("knowledge", "enabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("knowledge", "frozen", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("knowledge", "frozen", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("knowledge", "enabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("knowledge", "summary_entry")
    # ### end Alembic commands ###
