"""make message nullable

Revision ID: d63d1146dd16
Revises: 1ab1bd4ac856
Create Date: 2024-08-10 18:09:30.526185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63d1146dd16'
down_revision: Union[str, None] = '1ab1bd4ac856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
