"""add sender_name to messages

Revision ID: b9882f6c79fc
Revises: d63d1146dd16
Create Date: 2024-08-16 15:55:14.195438

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9882f6c79fc"
down_revision: str | None = "d63d1146dd16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("sender_name", sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "sender_name")
    # ### end Alembic commands ###
