"""changes to message table

Revision ID: ea4344179df8
Revises: 0d440b092601
Create Date: 2024-08-06 16:26:00.842095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4344179df8'
down_revision: Union[str, None] = '0d440b092601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('external_id', sa.Integer(), nullable=True))
    op.drop_column('message', 'message_tokens')
    op.drop_column('message', 'summary')
    op.drop_column('message', 'summary_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('summary_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('message_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('message', 'external_id')
    # ### end Alembic commands ###
