"""add spacy docs

Revision ID: 4b9a98eb28b8
Revises: c2874fb7d88f
Create Date: 2024-02-11 22:50:58.732341

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b9a98eb28b8"
down_revision: str | None = "c2874fb7d88f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("spacy_doc", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "spacy_doc")
    # ### end Alembic commands ###
