"""add field to segmented memories

Revision ID: 0b519949f5fc
Revises: f6391e0dc0e5
Create Date: 2025-02-21 12:55:26.152844

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b519949f5fc"
down_revision: str | None = "f6391e0dc0e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segmented_memories",
        sa.Column(
            "memory_entry", sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segmented_memories", "memory_entry")
    # ### end Alembic commands ###
